"""Live API tests for gmail_get_message tool.

These tests require:
- credentials.json in project root
- .token.json generated by running auth_cli.py
- Valid Gmail account

Run with: pytest -m live -v
"""

import pytest

from server.tools import GmailMcpTools


@pytest.mark.live
def test_get_message_full(live_gmail_tools):
    """Test getting message with full format."""
    # First, search for a message to get an ID
    search_result = live_gmail_tools.gmail_search_messages(
        query="in:inbox",
        max_results=1
    )
    
    if not search_result["results"]:
        pytest.skip("No messages found in inbox for testing")
    
    message_id = search_result["results"][0]["id"]
    
    # Get full message
    result = live_gmail_tools.gmail_get_message(
        message_id=message_id,
        fmt="full"
    )
    
    assert "id" in result
    assert result["id"] == message_id
    assert "headers" in result
    assert "From" in result["headers"] or "from" in result["headers"]
    assert "body_text" in result or "body_html" in result  # At least one body format


@pytest.mark.live
def test_get_message_metadata(live_gmail_tools):
    """Test getting message with metadata format."""
    # First, search for a message
    search_result = live_gmail_tools.gmail_search_messages(
        query="in:inbox",
        max_results=1
    )
    
    if not search_result["results"]:
        pytest.skip("No messages found in inbox for testing")
    
    message_id = search_result["results"][0]["id"]
    
    # Get metadata only
    result = live_gmail_tools.gmail_get_message(
        message_id=message_id,
        fmt="metadata"
    )
    
    assert "id" in result
    assert "headers" in result
    assert "body_text" not in result  # Should not include body in metadata format
    assert "body_html" not in result


@pytest.mark.live
def test_get_message_not_found(live_gmail_tools):
    """Test handling of non-existent message ID."""
    result = live_gmail_tools.gmail_get_message(
        message_id="nonexistent_12345",
        fmt="full"
    )
    
    assert "error" in result
    assert result["error"] == "not_found"


@pytest.mark.live
def test_get_message_headers_completeness(live_gmail_tools):
    """Test that headers include common fields."""
    # Get a message
    search_result = live_gmail_tools.gmail_search_messages(
        query="in:inbox",
        max_results=1
    )
    
    if not search_result["results"]:
        pytest.skip("No messages found in inbox for testing")
    
    message_id = search_result["results"][0]["id"]
    result = live_gmail_tools.gmail_get_message(
        message_id=message_id,
        fmt="full"
    )
    
    headers = result["headers"]
    # Check for common header fields (case-insensitive)
    header_names = [h.lower() for h in headers.keys()]
    assert any("from" in h for h in header_names) or any("subject" in h for h in header_names)


@pytest.mark.live
def test_get_message_body_decoding(live_gmail_tools):
    """Test that body is properly decoded."""
    # Get a message
    search_result = live_gmail_tools.gmail_search_messages(
        query="in:inbox",
        max_results=1
    )
    
    if not search_result["results"]:
        pytest.skip("No messages found in inbox for testing")
    
    message_id = search_result["results"][0]["id"]
    result = live_gmail_tools.gmail_get_message(
        message_id=message_id,
        fmt="full"
    )
    
    # Body should be decoded (not base64)
    if "body_text" in result:
        body = result["body_text"]
        # Should not contain base64 padding characters
        assert "=" not in body[-2:] or len(body) > 100  # Allow for normal = in content

