"""Live API tests for gmail_search_messages tool.

These tests require:
- credentials.json in project root
- .token.json generated by running auth_cli.py
- Valid Gmail account with test emails

Run with: pytest -m live -v
"""

import pytest

from server.tools import GmailMcpTools


@pytest.mark.live
def test_basic_search(live_gmail_tools):
    """Test basic search functionality."""
    result = live_gmail_tools.gmail_search_messages(
        query="in:inbox",
        max_results=5
    )
    
    assert "results" in result
    assert "total_count" in result
    assert result["total_count"] >= 0
    assert len(result["results"]) <= 5
    
    if result["results"]:
        first = result["results"][0]
        assert "id" in first
        assert "thread_id" in first


@pytest.mark.live
def test_subject_search(live_gmail_tools):
    """Test subject-based search."""
    # This test requires a known subject in your Gmail
    # Adjust the query to match your test emails
    result = live_gmail_tools.gmail_search_messages(
        query="in:inbox",
        max_results=10
    )
    
    if result["results"]:
        # Verify results have subject field (if enriched)
        first = result["results"][0]
        # Subject may be None if not enriched, which is OK
        assert "subject" in first


@pytest.mark.live
def test_from_search(live_gmail_tools):
    """Test from: filter search."""
    result = live_gmail_tools.gmail_search_messages(
        query="in:inbox",
        max_results=10
    )
    
    assert "results" in result
    # Verify structure even if no results match
    if result["results"]:
        first = result["results"][0]
        assert "from_email" in first


@pytest.mark.live
def test_newer_than_days_filter(live_gmail_tools):
    """Test newer_than_days filter."""
    result = live_gmail_tools.gmail_search_messages(
        query="",
        max_results=10,
        newer_than_days=3
    )
    
    assert "results" in result
    # Results should be from last 3 days (if any exist)


@pytest.mark.live
def test_label_ids_filter(live_gmail_tools):
    """Test label_ids filter."""
    result = live_gmail_tools.gmail_search_messages(
        query="",
        max_results=10,
        label_ids=["INBOX"]
    )
    
    assert "results" in result
    # Results should be from INBOX


@pytest.mark.live
def test_pagination(live_gmail_tools):
    """Test pagination with larger result set."""
    result_small = live_gmail_tools.gmail_search_messages(
        query="in:anywhere",
        max_results=5
    )
    
    result_large = live_gmail_tools.gmail_search_messages(
        query="in:anywhere",
        max_results=25
    )
    
    assert result_large["total_count"] >= result_small["total_count"]
    assert len(result_large["results"]) <= 25
    assert len(result_small["results"]) <= 5


@pytest.mark.live
def test_deduplication(live_gmail_tools):
    """Test that results are deduplicated."""
    result = live_gmail_tools.gmail_search_messages(
        query="in:anywhere",
        max_results=30
    )
    
    if result["results"]:
        ids = [r["id"] for r in result["results"]]
        assert len(ids) == len(set(ids))  # No duplicates


@pytest.mark.live
def test_empty_results(live_gmail_tools):
    """Test handling of empty search results."""
    result = live_gmail_tools.gmail_search_messages(
        query="from:nonexistent_z9x8y7@fakeemail.test",
        max_results=10
    )
    
    assert "results" in result
    assert result["total_count"] == 0
    assert result["results"] == []
    assert "hint" in result


@pytest.mark.live
def test_max_results_boundary(live_gmail_tools):
    """Test max_results boundary values."""
    result_1 = live_gmail_tools.gmail_search_messages(
        query="in:inbox",
        max_results=1
    )
    
    assert len(result_1["results"]) <= 1
    
    result_50 = live_gmail_tools.gmail_search_messages(
        query="in:inbox",
        max_results=50
    )
    
    assert len(result_50["results"]) <= 50


@pytest.mark.live
def test_complex_query(live_gmail_tools):
    """Test complex query combination."""
    result = live_gmail_tools.gmail_search_messages(
        query="in:inbox",
        max_results=10,
        newer_than_days=30,
        label_ids=["INBOX"]
    )
    
    assert "results" in result
    # Verify query was combined correctly (results should match all criteria)

